base/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('favorite/<int:post_id>/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite_page/', views.FavoritePageView.as_view(), name='favorite_page'),

]

base/base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from payment.views import go_to_gateway_view

from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('go-to-gateway/', go_to_gateway_view),
    path("bankgateways/", az_bank_gateways_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('prices/', views.PricesView.as_view(), name='prices'),
    path('topic_info/<int:topic_id>/', views.TopicInfoView.as_view(), name='Topic_info'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostView.as_view(), name='post'),
    path('like/<int:post_id>/', views.LikeView.as_view(), name='like'),
    path('dislike/<int:post_id>/', views.DislikeView.as_view(), name='dislike'),
    path('reply/<int:post_id>/<int:comment_id>', views.ReplyView.as_view(), name='reply'),
]

base/home/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey

class Topic(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    name = models.CharField(max_length=100,default='name')
    is_parent = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['name']
    def __str__(self):
        return self.name

class Post(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    issue = models.CharField(max_length=100,unique=True,default='')
    body = RichTextUploadingField()
    primary=models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created']
    def __str__(self):
        return f'{self.topic}-{self.created}'
    def number_of_likes(self):
        return self.plikes.count()
    def number_of_dislikes(self):
        return self.dplikes.count()

class LikePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulikes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='plikes')
    def __str__(self):
        return f'{self.user} like {self.post.slug}'
class DislikePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dulikes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='dplikes')
    def __str__(self):
        return f'{self.user} dislike {self.post.slug}'
class Comment(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='Ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='Pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies',null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-{self.post}-{self.body}'

base/home/forms.py
from django import forms

from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
       # widgets ={
        #    'body': forms.Textarea(attrs={'class': 'form-control'}),
        #}
        labels ={
            'body': 'Comment'
        }
class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
       # widgets ={
       #     'body': forms.Textarea(attrs={'class': 'form-control'}),
       # }
        labels ={
            'body': 'Reply',
        }
class ImageForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}))
    image = forms.ImageField()

class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

base/home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Topic, Post, LikePost, DislikePost,Comment
from .forms import CommentForm,ReplyForm,SearchForm
from accounts.models import is_subscribed


class HomeView(View):
    form_class = SearchForm

    def get(self, request):
        can_see=0
        topics = Topic.objects.filter()
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(issue__contains=request.GET['search'])
        if request.user.is_authenticated:
            can_see = is_subscribed(request.user)
        return render(request,'home/home.html',{'topics':topics,'posts':posts,'can_see':can_see,'form':self.form_class})
class PricesView(View):
    def get(self, request):
        return render(request,'home/prices.html')

class TopicInfoView(View):
    def get(self, request,*args, **kwargs):
        can_see=0
        topic = get_object_or_404(Topic,pk=kwargs['topic_id'])
        posts = topic.posts.all()
        if request.user.is_authenticated:
            can_see = is_subscribed(request.user)
        return render(request, 'home/topic_info.html',{'topic':topic,'posts':posts,'can_see':can_see})
class PostView(View):
    form_class = CommentForm
    from_class_reply = ReplyForm
    def setup(self, request, *args, **kwargs):
        self.post_instance=get_object_or_404(Post,pk=kwargs['post_id'],slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        comments = post.Pcomments.filter(is_reply=False)
        form = self.form_class()
        form_reply = self.from_class_reply()
        posts = Post.objects.filter(topic=post.topic)
        return render(request, 'home/post.html',{'post':post ,'comments':comments,'form':form,'form_reply':form_reply,'posts':posts})
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.post_instance
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'Your comment save successfully','success')
            return redirect('home:post', post.id, post.slug)
class LikeView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post,pk=kwargs['post_id'])
        like_post = LikePost.objects.filter(user=request.user, post=post)
        dislike_post = DislikePost.objects.filter(user=request.user, post=post)
        if like_post:
            like_post.delete()
            messages.error(request,'You are remove like this post','danger')
        elif dislike_post:
            dislike_post.delete()
            LikePost.objects.create(user=request.user, post=post)
            messages.success(request, 'You like this post successfully', 'success')
        else:
            LikePost.objects.create(user=request.user, post=post)
            messages.success(request,'You like this post successfully','success')
        return redirect('home:post', post.id,post.slug)
class DislikeView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post,pk=kwargs['post_id'])
        like_post = LikePost.objects.filter(user=request.user, post=post)
        dislike_post = DislikePost.objects.filter(user=request.user, post=post)
        if like_post :
            like_post.delete()
            DislikePost.objects.create(user=request.user, post=post)
            messages.success(request, 'You disliked this post successfully', 'success')
        elif dislike_post :
            dislike_post.delete()
            messages.error(request,'You remove disliked the post ','danger')
        else:
            DislikePost.objects.create(user=request.user, post=post)
            messages.success(request, 'You disliked this post successfully', 'success')
        return redirect('home:post', post.id, post.slug)
class ReplyView(View):
    form_class = ReplyForm
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post,pk=kwargs['post_id'])
        comment = get_object_or_404(Comment,pk=kwargs['comment_id'])
        form = self.form_class(request.POST)
        if form.is_valid():
            Reply = form.save(commit=False)
            Reply.user=request.user
            Reply.post = post
            Reply.reply = comment
            Reply.is_reply = True
            Reply.save()
            messages.success(request, 'Your reply save successfully','success')
            return redirect('home:post', post.id, post.slug)
        return redirect('home:post', post.id, post.slug)

base/home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
    {% for topic in topics %}
        <a href="{% url 'home:Topic_info' topic.id %}">{{ topic.name}}</a>
    {% endfor %}<br/>

    <form action="" method="get" class="col-md-4">
    {{ form.as_p }}
    <input type="submit" value="Search">
    </form><br/><br/>

   <div class="card">
        {% for post in posts %}
            {% if post.primary == 1 %}
                {% if can_see == 1 %}
                    <a class="card-body  red-text" href="{% url 'home:post' post.id post.slug %}">{{ post.issue|truncatewords:8 |safe }}</a><hr/>
                {% elif can_see == 0 and request.user.is_authenticated%}
                    <a class="card-body  red-text" href="{% url 'home:prices' %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% else %}
                    <a class="card-body  red-text" href="{% url 'accounts:login'  %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                    <a></a>
                {% endif %}

            {% else %}
                {% if request.user.is_authenticated %}
                    <a class="card-body " href="{% url 'home:post' post.id post.slug %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% else %}
                    <a class="card-body " href="{% url 'accounts:login'  %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

base/home/templates/home/post.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

{% block body %}
    <a class="btn btn-light" href="{% url 'accounts:favorite' post.id %}">Add to Favorite</a><br/><br/>
    <p><a href="{%  url  'home:Topic_info' post.topic.id %}">{{ post.topic.name }}</a> / {{ post.updated |date:'Y-M-D' }}</p>
    <a>{{ post.body|safe }}</a><br/><br/>

    <a class=" btn btn-blue col-md-1 " href="{% url 'home:like' post.id %}">Like {{ post.number_of_likes }}</a>
    <a class=" btn btn-red col-md-1 " href="{% url 'home:dislike' post.id %}">Dislike {{ post.number_of_dislikes}}</a><hr/>

    <h2>Suggestion:</h2><br/>
    {% for item in posts %}
        <a href="{% url 'home:post' item.id item.slug %}">{{ item.issue }}</a>
    {% endfor %}<br/><br/>

    <h2>Comments: </h2>
    {% if request.user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form><br/>
    {% else %}
        <p class="alert alert-danger">only login user can send comment</p>
    {% endif %}
    <p>{{ comments.count }} comments</p>
    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <p class="card-body">{{ comment.body }}</p>
            <form action="{% url 'home:reply' post.id comment.id %}" method="post">
                {% csrf_token %}
                {{ form_reply.as_p }}
                <input type="submit" value="Send">
            </form><br/>

            {% with replies=comment.replies.all%}
            {% for reply in replies %}
                <p class="card-body bg-primary p-3 m-2"><a>{{ reply.user }} | {{ reply.created|timesince }}</a><br/><br/>{{ reply.body }}</p>
            {% endfor %}
            {% endwith %}
        </div><br/>

    {% empty %}
        <p>there is not any comment on this post! </p>
    {% endfor %}
{% endblock %}

base/home/templates/home/prices.html
{% extends 'base.html' %}

{% block title %}Prices{% endblock %}

{% block body %}
    <h2 class="text-center">Prices</h2><hr/>
    <div class="card">
        <br/><a class="text-center" href="{% url 'accounts:profile' request.user.id %}?price={{ 30 }}">bye for month</a><br/><hr/>
        <br/><a class="text-center" href="{% url 'accounts:profile' request.user.id %}?price={{ 20 }}">bye for 20 days</a><br/><hr/>
        <br/><a class="text-center" href="{% url 'accounts:profile' request.user.id %}?price={{ 10 }}">bye for 10 days</a><br/><hr/>
    </div>
{% endblock %}

base/home/templates/home/topic_info.html
{% extends 'base.html' %}

{% block title %}topic_info{% endblock %}

{% block body%}
    <h2 class="text-center">{{ topic.name }}</h2>
    <div class="card">

    {% with topics=topic.children.all %}
    {% if topics %}
        <h3>children:</h3>
        {% for item in topics %}
            <a href="{% url 'home:Topic_info' item.id %}">{{ item.name }}</a>
        {% endfor %}
    {% endif %}
    </div>
    <div class="card">
    {% if posts %}
        <h3>posts:</h3>
        {% for post in posts %}
            {% if post.primary == 1 %}
                {% if can_see == 1 %}
                    <a class="card-body  red-text" href="{% url 'home:post' post.id post.slug %}">{{ post.issue|truncatewords:8 |safe }}</a><hr/>
                {% elif can_see == 0 and request.user.is_authenticated%}
                    <a class="card-body  red-text" href="{% url 'home:prices' %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% else %}
                    <a class="card-body  red-text" href="{% url 'accounts:login'  %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                    <a></a>
                {% endif %}

            {% else %}
                {% if request.user.is_authenticated %}
                    <a class="card-body " href="{% url 'home:post' post.id post.slug %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% else %}
                    <a class="card-body " href="{% url 'accounts:login'  %}">{{ post.issue|truncatewords:8|safe }}</a><hr/>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}


    </div>
{% endblock %}