base/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('favorite/<int:post_id>/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite_page/', views.FavoritePageView.as_view(), name='favorite_page'),

]

base/base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from payment.views import go_to_gateway_view

from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('go-to-gateway/', go_to_gateway_view),
    path("bankgateways/", az_bank_gateways_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('prices/', views.PricesView.as_view(), name='prices'),
    path('topic_info/<int:topic_id>/', views.TopicInfoView.as_view(), name='Topic_info'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostView.as_view(), name='post'),
    path('like/<int:post_id>/', views.LikeView.as_view(), name='like'),
    path('dislike/<int:post_id>/', views.DislikeView.as_view(), name='dislike'),
    path('reply/<int:post_id>/<int:comment_id>', views.ReplyView.as_view(), name='reply'),
]

base/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

base/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
      {% if request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'accounts:profile' request.user.id %}">Profile</a>
          <a class="navbar-brand" href="{% url 'home:prices' %}">Prices</a>
          <a class="navbar-brand" href="{% url 'accounts:favorite_page' %}">Favorite</a>
          <a class="navbar-brand" href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
          <a class="navbar-brand" href="{% url 'accounts:register' %}">Register</a>
          <a class="navbar-brand" href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    </div>
  </div>
</nav>