base/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('favorite/<int:post_id>/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite_page/', views.FavoritePageView.as_view(), name='favorite_page'),

]

base/base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from payment.views import go_to_gateway_view

from azbankgateways.urls import az_bank_gateways_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('go-to-gateway/', go_to_gateway_view),
    path("bankgateways/", az_bank_gateways_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('prices/', views.PricesView.as_view(), name='prices'),
    path('topic_info/<int:topic_id>/', views.TopicInfoView.as_view(), name='Topic_info'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostView.as_view(), name='post'),
    path('like/<int:post_id>/', views.LikeView.as_view(), name='like'),
    path('dislike/<int:post_id>/', views.DislikeView.as_view(), name='dislike'),
    path('reply/<int:post_id>/<int:comment_id>', views.ReplyView.as_view(), name='reply'),
]

base/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime,timedelta
from django.utils import timezone

from home.models import Post


class Subscription(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='used_with')
    created = models.DateTimeField(auto_now_add=True)
    time = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user} - {self.created}'


    def rest_of_time(self):
        total_duration = self.time * 24 * 60 * 60
        elapsed_time = (timezone.now() - self.created).total_seconds()
        remaining_time = total_duration - elapsed_time
        remaining_time = timedelta(seconds=remaining_time)
        return remaining_time

def is_subscribed(user):
    if Subscription.objects.filter(user=user).exists():
        return 1
    return 0

class MyFavorite(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='favorites')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='favorites')
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created']
    def __str__(self):
        return f'{self.user} - {self.post}'

base/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.exceptions import ValidationError


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'password'}))
    password_check=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'check password'}))
    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('Username already exists')
        return username
    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('Email already exists')
        return email
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_check = cleaned_data.get('password_check')
        if password and password_check and password != password_check:
            raise ValidationError('Passwords do not match')
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'password'}))

class EditProfileForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields =[]

base/accounts/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .forms import LoginForm, RegisterForm,EditProfileForm
from .models import Subscription, MyFavorite, is_subscribed
from home.models import Post


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You are already logged in','warning')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self,request):
        form = self.form_class()
        return render(request,self.template_name,{'form':form})
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(username=cd['username'],email=cd['email'],password=cd['password'])
            messages.success(request,'You are now registered  ','success')
            return redirect('home:home')
        return render(request,self.template_name,{'form':form})
class LoginView(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You are already logged in','warning')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form=self.form_class()
        return render(request,self.template_name,{'form':form})
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'You are now logged in','success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            else:
                messages.error(request,' username or password is not correct','error')
        return render(request,self.template_name,{'form':form})
class LogoutView(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        messages.success(request,'You are now logged out','success')
        return redirect('home:home')

class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'
class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'
class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')
class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

class ProfileView(LoginRequiredMixin,View):
    def get(self,request,*args, **kwargs):
        user=User.objects.get(id=kwargs['user_id'])
        time1 = request.GET.get('price')


        if Subscription.objects.filter(user=user).exists():
            extra=Subscription.objects.filter(user=user).first()
            if time1 and time1.isdigit():
                time1=int(time1)
                extra.time=int(extra.time)+int(time1)
                extra.save()
                return redirect('accounts:profile',request.user.id)
            rest_time = extra.rest_of_time()
            return render(request,'accounts/profile.html',{'user':user,'rest_time':rest_time})

        if time1 and time1.isdigit() and not Subscription.objects.filter(user=user).exists():
            time1=int(time1)
            Subscription.objects.create(user=user,time=time1)
            return redirect('accounts:profile', request.user.id)
        else:
            time1 = 0
        return render(request,'accounts/profile.html',{'user':user,'rest_time':0})
class EditProfileView(LoginRequiredMixin,View):
    form_class = EditProfileForm
    template_name = 'accounts/edit_profile.html'
    def get(self,request,*args, **kwargs):
        form = self.form_class(initial={'username':request.user.username,'email':request.user.email,'first_name':request.user.first_name,'last_name':request.user.last_name})
        return render(request,'accounts/edit_profile.html',{'form':form})

    def post(self,request,*args, **kwargs):
        form=self.form_class(request.POST,initial={'username':request.user.username,'email':request.user.email,'first_name':request.user.first_name,'last_name':request.user.last_name})
        if form.is_valid():
            cd = form.cleaned_data
            request.user.username = cd['username']
            request.user.email = cd['email']
            request.user.first_name = cd['first_name']
            request.user.last_name = cd['last_name']
            request.user.save()
            messages.success(request,'You are now logged in','success')
            return redirect('accounts:profile',request.user.id)

class FavoriteView(LoginRequiredMixin,View):
    def get(self,request,*args, **kwargs):
        post = Post.objects.get(id=kwargs['post_id'])
        favorite = MyFavorite.objects.filter(user=request.user , post=post).exists()
        if favorite:
            messages.warning(request,'You are choose this post as your favorite at last','warning')
        elif not favorite and post.primary == True and is_subscribed(request.user) == 0:
            return redirect('home:prices')
        elif not favorite:
            MyFavorite.objects.create(user=request.user,post=post)
            messages.success(request,'You are choose this post as favorite now', 'success')
            return redirect('home:post',post.id, post.slug)
        return redirect('home:post',post.id, post.slug)
class FavoritePageView(View):
    def get(self,request,*args, **kwargs):
        favorites = request.user.favorites.all()
        return render(request,'accounts/favorite_page.html',{'favorites':favorites})

base/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block title %}Edit profile{% endblock %}

{% block body %}
    <form action="" method="post"  class="col-md-6">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit" class="col-md-2">
    </form>
{% endblock %}

base/accounts/templates/accounts/favorite_page.html
{% extends 'base.html' %}

{% block title %}Favorite{% endblock %}

{% block body %}
        {% for favorite in favorites %}
            <div class="card">
                <a class="card-header bg-primary text-white">{{ favorite.post.topic.topic }} | {{ favorite.created }}</a>
                <a class="card-body {% if favorite.post.primary %}red-text{% endif %}" href="{% url 'home:post'  favorite.post.id favorite.post.slug %}" >{{ favorite.post.issue|truncatewords:8 |safe}}</a>
            </div>
        {% endfor %}
{% endblock %}

base/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block body %}

    <form action="" method="post" class="col-md-6" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
    </form>
    <a href="{% url 'accounts:reset_password' %}">Forget your password</a>

{% endblock %}

base/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}complete page{% endblock %}

{% block body %}
    <p>Your password changed</p>
{% endblock %}

base/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}confirm page{% endblock %}

{% block body %}
    {% if validlink %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
    {% else %}
        <p>this link is not valid please try again</p>
    {% endif %}
{% endblock %}

base/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}reset done page{% endblock %}

{% block body %}<p>We send you an email</p>{% endblock %}

base/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

base/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Reset password form{% endblock %}

{% block body %}
    <p>enter your email for get a new password</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send">
    </form>

{% endblock %}

base/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block body %}
    <h2 class="text-center">{{ user.username }}</h2><hr/>
    <a href="{% url 'accounts:favorite_page' %}">Your favorite post</a>
    <div class="card">
        <p class="card-body">-username: {{ user.username }}<br/>-emai: {{ user.email }}<br/>-firstname: {{ user.first_name }}<br/>-lastname: {{ user.last_name }}<br/>-rest of your subscription: {{rest_time }}<br/><a href="{% url 'accounts:reset_password' %}">Change the password</a> </p>
    </div>
    <br/>
    <div class="row">
    <div class="col-md-12 text-left">
        {% if request.user.id == user.id %}
            <a class="btn btn-primary col-md-2 btn-left" href="{% url 'accounts:edit_profile' %}">Edit</a>
        {% endif %}
        <a class="btn btn-light col-md-2 btn-left" href="{% url 'home:home' %}">Exit</a>
    </div>
</div>

{% endblock %}

base/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block body %}

    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

{% endblock %}